/** Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

                            1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms
*/

#include<iostream>

void fibonacci_seq(int* sum,int num_1,int num_2,int max){

    if(num_2 % 2 == 0)
        *sum += num_2;
    if((num_1+num_2) > max)
        return;

    fibonacci_seq(sum,num_2,(num_1 + num_2),max);
}

int main(){

    int sum = 0;
    // int max = 4000000
    int max = 4000000;
    fibonacci_seq(&sum,1,2,max);

    std::cout << sum << std::endl;
    return 0;
}
